
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>PHP Layout</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/justified-nav/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="justified-nav.css" rel="stylesheet">
    <link rel="stylesheet" href="css/bs_styles.css">

  </head>

  <body>

    <div class="container">

      <header class="masthead">
        <a href="?page=home">
        <h3 class="text-muted">PHP Layout</h3>
        </a>
        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
              <li class="nav-item <?php echo is_active($page,'home');?>">
                <a class="nav-link" href="?page=home">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item <?php echo is_active($page,'test');?>">
                <a class="nav-link" href="?page=test">Test</a>
              </li>
              <li class="nav-item <?php echo is_active($page,'cars');?>">
                <a class="nav-link" href="?page=cars">Cars</a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <?php
        include $main_content;
      ?>
      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Chad is gay 1994 - 2020</p>
      </footer>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
