<h1>View Car</h1>
<table class="table table-hover">
<thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Car</th>
      <th scope="col">Car Type</th>
      <th scope="col">Year</th>
      <th scope="col">Price</th>
      <th scope="col">Opt. 1</th>
      <th scope="col">Opt. 2</th>
    </tr>
<?php

  foreach ($cars as $car) {
    $car_fields = explode(',',$car);
    echo '<tr>';
    foreach($car_fields as $field) {
     echo '<td>' . $field . '</td>'; 
    }
    echo '<td><a href="?page=cars&action=delete&id=' . $car_fields[0] . '">Delete</td>';
    echo '<td><a href="?page=cars&action=update&id=' . $car_fields[0] . '">Update</td>';
  }

?>
</table>